In [1]:
import numpy as np
from sklearn import preprocessing

In [3]:
x=np.array([[1.,-2,1.],
           [0.,1.,-1.],
           [-1.,0.,2.]])

In [4]:
x_scaled= preprocessing.scale(x)

In [5]:
x_scaled

array([[ 1.22474487, -1.33630621,  0.26726124],
       [ 0.        ,  1.06904497, -1.33630621],
       [-1.22474487,  0.26726124,  1.06904497]])

In [8]:
x_scaled.mean(axis=0)

array([  0.00000000e+00,  -3.70074342e-17,   1.48029737e-16])

In [10]:
x_scaled.std(axis=0)

array([ 1.,  1.,  1.])

In [11]:
scaler=preprocessing.StandardScaler()

In [13]:
scaler.fit(x)
scaler.transform(x)

array([[ 1.22474487, -1.33630621,  0.26726124],
       [ 0.        ,  1.06904497, -1.33630621],
       [-1.22474487,  0.26726124,  1.06904497]])

In [15]:
x_test=[[1,1,0]]
scaler.transform(x_test)

array([[ 1.22474487,  1.06904497, -0.53452248]])

In [21]:
data=[[0,3],[9,4],[2,7],[1,1]]
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [22]:
first=scaler.transform(data)

In [23]:
test=[[2,13],[1,4],[10,7],[1,9]]
second=scaler.transform(test)

In [24]:
print(first.sum())
print(second.sum())

0.0
8.87952930128
