In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T

In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
def derivativesig(z):
    return sig(z)*(1 - sig(z))

In [6]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[-0.36732383],
        [ 0.91313517]]), array([-0.07378475]))

In [7]:
#without any hidden layer output
for iter in range(10000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)
    fist_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativesig(input_for_last_layer)
    
    first_two=fist_term*second_term


    change=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            change[i][0]+=first_two[j][0] * output0[j][i]
    
    weights= weights-  lr*change
    
    bias_change=0.0

    for j in range(4):
        bias_change+=first_two[j][0]*1
    bias=bias-lr*bias_change
    
output=sig(np.dot(x,weights) + bias)
weights,bias,output

(array([[5.47893103],
        [5.47893106]]), array([-8.31109088]), array([[2.45715393e-04],
        [5.56108587e-02],
        [5.56108573e-02],
        [9.33811707e-01]]))

In [11]:
# optimization using vector operation 
for itr in range(10000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)
    fist_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativesig(input_for_last_layer)
    
    first_two=fist_term*second_term


    change=np.dot(output0.T,first_two)
    
    weights= weights-  lr*change
    
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change
    
output=sig(np.dot(x,weights) + bias)
weights,bias,output

(array([[6.72395703],
        [6.72395703]]), array([-10.17457998]), array([[3.81258472e-05],
        [3.07502872e-02],
        [3.07502872e-02],
        [9.63502597e-01]]))

In [8]:
#one hidden layer with two units
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [9]:
output0=x
outputhidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputhidden,wo)+bo)
output

array([[0.24963192],
       [0.22603363],
       [0.26965041],
       [0.24259892]])